In [1]:
import pandas as pd

In [10]:

data = { 'Name': ['Alice','Bob', 'Charlie'], 'Age': [24,27,22], 'City': ['New York', 'Los Angles', 'Chicago']}
# df = pd.DataFrame(data)
df = pd.DataFrame(data, index = ['a','b', 'c'])

In [16]:
# Location (loc[])

# print (df.loc["a"])
df.loc [["a","c"]]
# df.loc["a","City"]


#loc df.loc [row label, column ]

      Name  Age      City
a    Alice   24  New York
c  Charlie   22   Chicago

In [19]:
# Integer based location, iloc[]
df.iloc[0:3,1:3]

   Age        City
a   24    New York
b   27  Los Angles
c   22     Chicago

## Cleaning data (Droping columns)

In [24]:
practice_list = [
    {'Item': 'Apple', 'Qty': 10, 'Price': 0.5},
    {'Item': 'Banana', 'Qty': 5, 'Price': 0.3},
    {'Item': 'Cherry', 'Qty': 20, 'Price': 0.2},
    {'Item': 'Date', 'Qty': 7, 'Price': 0.4},
]
practice_df = pd.DataFrame(practice_list, index=['p1', 'p2', 'p3', 'p4'])
practice_df


#axis = 0 (drop row)
print(practice_df.drop("p1"))
print (practice_df)

print ()
#axis = 1 (drop column)
print(practice_df.drop("Qty", axis=1))
print (practice_df)

      Item  Qty  Price
p2  Banana    5    0.3
p3  Cherry   20    0.2
p4    Date    7    0.4
      Item  Qty  Price
p1   Apple   10    0.5
p2  Banana    5    0.3
p3  Cherry   20    0.2
p4    Date    7    0.4

      Item  Price
p1   Apple    0.5
p2  Banana    0.3
p3  Cherry    0.2
p4    Date    0.4
      Item  Qty  Price
p1   Apple   10    0.5
p2  Banana    5    0.3
p3  Cherry   20    0.2
p4    Date    7    0.4

In [ ]:
practice_null_df = pd.DataFrame({
    'Customer': ['Alice', None, 'Charlie', 'David'],
    'Age': [25, pd.NA, 30, 22],
    'City': ['New York', 'Los Angeles', None, 'Chicago'],
    'SignupDate': [pd.Timestamp('2021-01-01'), pd.NaT, pd.Timestamp('2021-03-15'), None],
    'Active': [True, pd.NA, False, None],
    'Spend': [100.0, None, 50.5, 0.0]
}, index=['n1', 'n2', 'n3', 'n4'])

print(practice_null_df)
print("========")
print(practice_null_df.isnull().sum())

print()
print("========")

#remove rows with null values
print (practice_null_df.dropna())

print()
print("========")

# remove columns with null values 

print (practice_null_df.dropna(axis=1))

print()
print("========")

print (practice_null_df.dropna(subset=['Customer']))


print()
print("========")

   Customer   Age         City SignupDate Active  Spend
n1    Alice    25     New York 2021-01-01   True  100.0
n2     None  <NA>  Los Angeles        NaT   <NA>    NaN
n3  Charlie    30         None 2021-03-15  False   50.5
n4    David    22      Chicago        NaT   None    0.0
========
Customer      1
Age           1
City          1
SignupDate    2
Active        2
Spend         1
dtype: int64

========
   Customer Age      City SignupDate Active  Spend
n1    Alice  25  New York 2021-01-01   True  100.0

========
Empty DataFrame
Columns: []
Index: [n1, n2, n3, n4]

========
   Customer Age      City SignupDate Active  Spend
n1    Alice  25  New York 2021-01-01   True  100.0
n3  Charlie  30      None 2021-03-15  False   50.5
n4    David  22   Chicago        NaT   None    0.0

========

## Filling in Null Values

In [49]:

# print (practice_null_df.fillna(0))
# print()
# print("========")

print (practice_null_df['Customer'].fillna('Unknown'))
print()
print("========")

print (practice_null_df['Age'].fillna(practice_null_df['Age'].mean()))
print()
print("========")

print (practice_null_df['City'].fillna('Unknown'))
print()
print("========")

print (practice_null_df['SignupDate'].fillna('Unknown'))
print()
print("========")

print (practice_null_df['Active'].fillna('Unknown'))
print()
print("========")


print (practice_null_df['Spend'].fillna(0))
print()
print("========")

n1      Alice
n2    Unknown
n3    Charlie
n4      David
Name: Customer, dtype: object

========
n1    25.000000
n2    25.666667
n3    30.000000
n4    22.000000
Name: Age, dtype: float64

========
n1       New York
n2    Los Angeles
n3        Unknown
n4        Chicago
Name: City, dtype: object

========
n1    2021-01-01 00:00:00
n2                Unknown
n3    2021-03-15 00:00:00
n4                Unknown
Name: SignupDate, dtype: object

========
n1       True
n2    Unknown
n3      False
n4    Unknown
Name: Active, dtype: object

========
n1    100.0
n2      0.0
n3     50.5
n4      0.0
Name: Spend, dtype: float64

========

/var/folders/kv/w46n1gj966xf84g50nqp00280000gn/T/ipykernel_44778/418360345.py:9: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print (practice_null_df['Age'].fillna(practice_null_df['Age'].mean()))